version: '3.2'

services:

  explorer-api:
    build: explorer-api/.
    image: polkascan/pre-explorer-api:latest
    hostname: explorer-api
    volumes:
      - './explorer-api:/usr/src/app'
    command: ./start.sh
    environment:
      - PYTHONPATH=/usr/src/app
      - ENVIRONMENT=prod
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=polkascan
      - SUBSTRATE_RPC_URL=http://substrate-node:9933/
      - SUBSTRATE_ADDRESS_TYPE=69
      - TYPE_REGISTRY=default
      - TYPE_REGISTRY_FILE=app/type_registry/custom_types.json
      - SUBSTRATE_METADATA_VERSION=12
    depends_on:
      - mysql
      - substrate-node

  harvester-api:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    hostname: harvester-api
    volumes:
      - './harvester:/usr/src/app'
    command: ./start.sh
    environment: &env
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/usr/src/app:/usr/src/app/py-substrate-interface/:/usr/src/app/py-scale-codec/
      - ENVIRONMENT=prod
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=polkascan
      - SUBSTRATE_RPC_URL=http://substrate-node:9933/
      - TYPE_REGISTRY=default
      - TYPE_REGISTRY_FILE=app/type_registry/custom_types.json
      - SUBSTRATE_ADDRESS_TYPE=69
      - SUBSTRATE_METADATA_VERSION=12
      - NEW_SESSION_EVENT_HANDLER=True
      - SUBSTRATE_STORAGE_BALANCE=Account
      - SUBSTRATE_STORAGE_INDICES=Accounts
    depends_on:
      - redis
      - mysql
      - substrate-node

  harvester-worker:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
    command: celery -A app.tasks worker --loglevel=INFO
    environment: *env
    depends_on:
      - redis
      - mysql

  harvester-beat:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    volumes:
      - './harvester:/usr/src/app'
      - '/usr/src/app/data'
    command: celery -A app.tasks beat --loglevel=INFO  --schedule="data/celerybeat-schedule" --pidfile="data/celerybeat.pid"
    environment: *env
    depends_on:
      - redis

  harvester-monitor:
    build: harvester/.
    image: polkascan/pre-harvester:latest
    command: celery -A app.tasks --broker=redis://redis:6379/0 flower
    ports:
      - '5555:5555'
    depends_on:
      - redis

  redis:
    image: redis:3.2.11
    hostname: redis

  mysql:
    image: mysql:8.0.23
    hostname: mysql
    volumes:
      - 'db-data:/var/lib/mysql'
    ports:
      - '33061:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=polkascan

  substrate-node:
    image: sora2/substrate:1.0.0
    volumes:
      - 'substrate-data:/data'
    command: --name sora2-node --chain main --base-path /chain --unsafe-ws-external --unsafe-rpc-external --pruning archive --rpc-cors all

  explorer-gui:
    image: polkascan/pre-explorer-gui:latest
    build:
      context: explorer-gui/.
      args:
        NETWORK_NAME: SORA
        NETWORK_ID: sora
        NETWORK_TYPE: pre
        CHAIN_TYPE: para
        NETWORK_TOKEN_SYMBOL: XOR
        NETWORK_TOKEN_DECIMALS: 18
        NETWORK_COLOR_CODE: c6021a
        API_URL: http://127.0.0.1:8080/api/v1
    ports:
      - '8080:80'
    depends_on:
      - harvester-api
      - explorer-api

  polkadot-ui:
    image: polkasource/substrate-ui:polkadot-latest
    ports:
      - '8081:80'

volumes:
  db-data:
  substrate-data:
